# Generated by Django 5.2 on 2025-04-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.IntegerField(default=1)),
                ('camera', models.CharField(default=None, max_length=100)),
                ('light', models.CharField(default=None, max_length=100)),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='product.production')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=200)),
                ('resolution', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=100)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspection.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default=None)),
                ('is_defect', models.BooleanField(default=False)),
                ('inspection_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='inspection.inspectionimage')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedInspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=100)),
                ('defect_position', models.CharField(max_length=100)),
                ('inspection_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inspection.inspectionresult')),
            ],
        ),
    ]
