# Generated by Django 5.1.7 on 2025-05-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionimage',
            name='resolution',
        ),
        migrations.AlterField(
            model_name='inspectionimage',
            name='image_path',
            field=models.ImageField(upload_to='inpection'),
        ),
    ]
