# Generated by Django 5.2 on 2025-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_type', models.CharField(max_length=100)),
                ('specification', models.CharField(default=None, max_length=100)),
                ('order', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
