# Generated by Django 5.1.7 on 2025-05-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='product_image',
            field=models.ImageField(null=True, upload_to='original'),
        ),
    ]
