# Generated by Django 5.1.7 on 2025-05-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_production_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='product_image',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
